### ISSUE TITLE
WebDAV password

### ISSUE THREAD

**Issue by Pe0xonN** [divyam234/rclone-browser#1]
Where to enter the password for WebDAV, because I don't have this option, and WebDAV always has a password

**Comment by divyam234** [comment]
auth will not be possible unless this ui is integrated into server itself

**Comment by Pe0xonN** [comment]
How to do it on huggingface

**Comment by Pe0xonN** [comment]
> huggingface

Why it doesn't work on huggingface

**Comment by Pe0xonN** [comment]
> auth will not be possible unless this ui is integrated into server itself

Why it doesn't work on huggingface
